### ISSUE TITLE
Issue with enableClickToDial & disableClickToDial methods

### ISSUE THREAD

**Issue by raghuvirodhula** [developerforce/open-cti-demo-adapter#1]
Hi David,

We are trying to implement Open CTI in Lightning experience in one of our orgs. We installed Lightning Open CTI according to the document and made all the required configurations/settings. When we launch Open CTI and click on Log In (after entering username & password), it does nothing. We debugged it and found that in ctiLoginPanelHelper.js, it is not invoking the enableClickToDial method when we click on login button. The domain name for this org contains double hyphen (--). When we reinstall in another org with a different domain name (domain name without hyphen) it works. We are not sure whether there is a problem with the domain name.

Regards,
Raghu

**Comment by dlouvton** [comment]
Thanks Raghu. I'm not sure that My Domain can contain a double hyphen, but I'll double check.
Hopefully you are not being blocked, once you used a different domain name without hyphens.

**Comment by dlouvton** [comment]
closing this issue -- it seems that My Domain cannot contain a double hyphen.

**Comment by raghuvirodhula** [comment]
hi David, if we are creating a domain in sandbox it will contain "--"(same as in my case). Could you please suggest how do we handle this issue in those situations?
