### ISSUE TITLE
Error in trying to make a call with tiwilio

### ISSUE THREAD

**Issue by jjbala1983** [developerforce/open-cti-demo-adapter#3]
Getting following error after trying to make a call

Uncaught Error: Unable to make a call. Contact your admin. throws at components/c/callInitiatedPanel.js:57:37

**Comment by moometric** [comment]
Ah, i'm not the only one! Same error.
Everything seems to work fine when testing with the dummy calling, the moment I add the twilio settings, it bombs with this error.

![image](https://cloud.githubusercontent.com/assets/15805783/25978331/9f599158-368f-11e7-8ed0-af49c43d998e.png)

**Comment by moometric** [comment]
@jjbala1983 - I had the same issue. Just ran a test and noticed that if you try and dial a phone number which has no associated contact, it crashed with this error. But if you click to dial from a contact, it appears to work. Not sure if you can replicate the same on your side?

**Comment by jjbala1983** [comment]
Yes. I did.

Much appreciated your response.


Regards,
Jayabalan Jayaraman | Salesforce.com
Product Architect – Tech Mahindra
jayabalan.jayaraman@techmahindra.com<mailto:jayabalan.jayaraman@techmahindra.com>

Cell: +91 9597464614

**Comment by dlouvton** [comment]
Thanks for the clarification. I'll take a look.

**Comment by manzanofab** [comment]
Did anyone find a solution for this? getting same error, from either a contact or direct number

**Comment by avnishyadav25** [comment]
Did anyone find the solution available? please share with us.

**Comment by Maxxpower** [comment]
Same error: Uncaught Error: Unable to make a call. Contact your admin. visualforce.com/components/c/callInitiatedPanel.js:57:43   it seems that from a brief code review the component recordId attribute is always empty. Even if I try to call from a contact.

**Comment by codesilo4** [comment]
Make sure that the number you are trying to call is a verified number on your Twilio account (in case of trial accounts). https://www.twilio.com/console/phone-numbers/verified
If you try to call an unverified number, you get this same exception message.

**Comment by avnishyadav25** [comment]
I found a solution, hope this will help you-
1. Re-check your accoundSid and Token
2. Add the no. to your Twilio account in phone number section and also verified that number.
Thanks.
